import Image from 'next/image';
import { Brand, Container, Icon, LinkButton } from '@/shared/ui';
import { CaseMetrics } from '@/entities/case';
import { milestones, stages } from './content';
import { HeroVisual } from './hero-visual';
import s from './landing-content.module.css';
export function LandingHero(){return <section className={s.hero} aria-labelledby="hero-title"><Container className={s.hero__grid}><div className={s.hero__copy}><span className={s.hero__badge}><span/>Аккредитованная IT-компания</span><h1 id="hero-title">Разработка<br/>программного<br/>обеспечения <span>20+ лет</span></h1><div className={s.hero__actions}><LinkButton href="#request">Получить расчёт проекта</LinkButton><LinkButton href="#portfolio" variant="secondary">Изучить портфолио<Icon/></LinkButton></div></div><HeroVisual className={s.hero__visual}/></Container></section>}
export function Chronicle(){return <div className={s.chronicle} aria-label="Хроника компании"><div className={s.chronicle__track}>{[0,1].map(copy=><div key={copy} className={s.chronicle__items} aria-hidden={copy===1?true:undefined}>{milestones.map(item=><span key={item}>{item}</span>)}</div>)}</div></div>}
export function Manifest(){return <section id="about" className={s.manifest} aria-label="Инженерный манифест"><Container><blockquote className={s.manifest__panel}><span>Инженерный манифест</span><p>Надёжный софт — как точный инженерный расчёт:<br/>ни единой лишней строки, безупречная работа<br className={s.manifest__break}/> десятилетиями.</p></blockquote></Container></section>}
export function Portfolio(){return <section id="portfolio" className={s.portfolio} aria-labelledby="portfolio-title"><Container><div className={s.portfolio__heading}><h2 id="portfolio-title">Портфолио реализованных систем</h2><a href="#case">Все кейсы в портфолио<Icon/></a></div></Container><div className={s.portfolio__logos} aria-label="Клиент М.Видео">{Array.from({length:5},(_,i)=><div className={s.portfolio__logo} key={i} aria-hidden={i>0?true:undefined}><Image src="/landing/mvideo.svg" width={208} height={60} alt={i===0?'М.Видео':''}/></div>)}</div><Container><article id="case" className={s.portfolio__case}><div className={s.portfolio__image}><Image src="/landing/case.png" alt="Центр управления омниканальной платформой заказов" fill sizes="(max-width: 767px) 90vw, 405px"/></div><div className={s.portfolio__copy}><h3>Омниканальная<br/>платформа заказов</h3><p>Единая система управления заказами, объединяющая интернет-магазин и розничную сеть.</p><CaseMetrics layout="rows" metrics={[{value:'+22%',label:'скорости обработки заказов'},{value:'4 200',label:'магазинов'}]}/><details className={s.portfolio__details}><summary>Подробнее<Icon/></summary><p>Омниканальная платформа объединяет интернет-магазин и розничную сеть в единую систему управления заказами.</p><a href="#request">Обсудить похожую задачу</a></details></div></article></Container></section>}
export function DevelopmentStages({children}:{children:React.ReactNode}){return <section id="workflow" className={s.workflow} aria-labelledby="workflow-title"><Container><h2 id="workflow-title">5 этапов создания безупречного ПО</h2><div className={s.workflow__list}>{children}</div></Container></section>}
export { stages };
export function SiteFooter(){return <footer id="contacts" className={s.footer}><Container><div className={s.footer__brand}><Brand/><p>Инженерия и разработка программного обеспечения</p></div><div className={s.footer__columns}><div><h2>Контакты</h2><address>117342, г. Москва,<br/>ул. Профсоюзная, д. 65, оф. 412<br/><a href="tel:+74951234567">+7 (495) 123-45-67</a><br/><a href="mailto:info@siriustech.ru">info@siriustech.ru</a></address></div><div><h2>Услуги</h2><a href="#services">Заказная разработка ПО</a><a href="#services">Сайты и корпоративные порталы</a><a href="#services">Мобильные приложения</a><a href="#request">Интеграция с 1С</a><a href="#request">Выделенные команды</a><a href="#request">Техподдержка SLA 24/7</a></div><div><h2>О компании</h2><a href="#top">Главная</a><a href="#services">Услуги</a><a href="#portfolio">Портфолио</a><a href="#about">О компании</a><a href="#workflow">Методология</a><a href="#contacts">Контакты</a></div><div><h2>Гарантии & стандарты</h2><p>12 месяцев безусловной гарантии на код.</p><p>Передача исключительных авторских прав на ПО заказчику в полном объёме по договору.</p><span className={s.footer__policy}>Политика конфиденциальности</span></div></div><div className={s.footer__bottom}><p>© 2004–2025 ООО «СириусТех». Все права защищены.</p><p>Фундаментальный подход к цифровым решениям</p></div></Container></footer>}
